# Generated by Django 3.0.6 on 2020-05-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('body', models.CharField(max_length=30, null=True)),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
    ]
