# Generated by Django 3.0.6 on 2020-05-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepictures',
            name='images',
        ),
    ]
