# Generated by Django 3.0.6 on 2020-05-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_remove_homepictures_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepictures',
            name='images',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
