# Generated by Django 3.0.6 on 2020-05-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_homepictures_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepictures',
            name='images',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
