# Generated by Django 3.0.6 on 2020-05-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_auto_20200505_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepictures',
            name='images',
            field=models.ImageField(null=True, upload_to='carousel'),
        ),
    ]
