# Generated by Django 3.0.6 on 2020-05-05 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_auto_20200506_0023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepictures',
            options={'verbose_name': 'Website Top Image', 'verbose_name_plural': 'Website Top Images'},
        ),
    ]
