# Generated by Django 3.0.6 on 2020-05-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_auto_20200506_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=10)),
                ('card_text', models.CharField(max_length=100)),
                ('images', models.ImageField(null=True, upload_to='carousel')),
                ('card_body', models.CharField(max_length=5000)),
            ],
            options={
                'verbose_name': 'Website Card Image',
            },
        ),
        migrations.AlterModelOptions(
            name='homepictures',
            options={'verbose_name': 'Website Carousel Image', 'verbose_name_plural': 'Website Top Images'},
        ),
    ]
