# Generated by Django 3.0.6 on 2020-05-06 12:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_auto_20200506_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepictures',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 5, 6, 12, 30, 6, 370903, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
