# Generated by Django 3.0.6 on 2020-05-06 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0012_auto_20200507_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='more_body',
            field=models.CharField(default='wewewewewewewew', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='body',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 7, 0, 22, 3, 375753)),
        ),
    ]
