# Generated by Django 3.0.6 on 2020-05-06 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0013_auto_20200507_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000)),
                ('heading2', models.CharField(max_length=100)),
                ('body2', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterField(
            model_name='contactform',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 7, 0, 29, 21, 121009)),
        ),
    ]
