# Generated by Django 3.0.6 on 2020-05-07 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0014_auto_20200507_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classabout',
            name='body',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='classabout',
            name='body2',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='classabout',
            name='heading',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='classabout',
            name='heading2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 7, 22, 57, 37, 139301)),
        ),
    ]
