# Generated by Django 3.0.6 on 2020-05-07 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0015_auto_20200507_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classabout',
            name='body',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='classabout',
            name='body2',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 0, 1, 17, 607997)),
        ),
    ]
