# Generated by Django 3.0.6 on 2020-05-07 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0022_auto_20200508_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanceStyleWeTeach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('dance_style', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='dance_styles')),
            ],
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(default='static/images/g1.jpg', upload_to='about_us'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='more_popup_image',
            field=models.ImageField(upload_to='about_us'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 0, 57, 7, 406429)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 0, 57, 7, 409425)),
        ),
    ]
