# Generated by Django 3.0.6 on 2020-05-07 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0023_auto_20200508_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultiesProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='dance_masters')),
                ('name', models.CharField(max_length=20)),
                ('facebook_link', models.URLField(null=True)),
                ('instagram_link', models.URLField(null=True)),
                ('youtube_link', models.URLField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contactform',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 1, 25, 49, 491630)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 1, 25, 49, 495626)),
        ),
    ]
