# Generated by Django 3.0.6 on 2020-05-07 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0024_auto_20200508_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunkFactoryGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=2000)),
                ('location', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='gallery')),
                ('background_image', models.ImageField(null=True, upload_to='gallery')),
                ('link', models.URLField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contactform',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 1, 55, 42, 230885)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 1, 55, 42, 246508)),
        ),
    ]
