# Generated by Django 3.0.6 on 2020-05-07 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0025_auto_20200508_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 2, 10, 4, 682706)),
        ),
        migrations.AlterField(
            model_name='funkfactorygallery',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='funkfactorygallery',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='funkfactorygallery',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 2, 10, 4, 682706)),
        ),
    ]
