# Generated by Django 3.0.6 on 2020-05-07 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0026_auto_20200508_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 2, 14, 27, 164130)),
        ),
        migrations.AlterField(
            model_name='facultiesprofile',
            name='facebook_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='facultiesprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='dance_masters'),
        ),
        migrations.AlterField(
            model_name='facultiesprofile',
            name='instagram_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='facultiesprofile',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='funkfactorygallery',
            name='likes',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 2, 14, 27, 164130)),
        ),
    ]
