# Generated by Django 3.0.6 on 2020-05-08 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0032_auto_20200508_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwords',
            old_name='passwords',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='passwords',
            name='userid',
        ),
        migrations.AlterField(
            model_name='contactform',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 12, 14, 48, 512410)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 12, 14, 48, 515408)),
        ),
    ]
