# Generated by Django 3.0.6 on 2020-05-10 12:56

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0035_auto_20200509_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, max_length=10)),
                ('timing', models.CharField(blank=True, max_length=10)),
                ('price', models.CharField(blank=True, max_length=10)),
                ('rating', models.CharField(blank=True, max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Cards',
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us', 'verbose_name_plural': '2 About Us'},
        ),
        migrations.AlterModelOptions(
            name='classabout',
            options={'verbose_name': 'personalise about class', 'verbose_name_plural': '4 personalise about class'},
        ),
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': 'Details', 'verbose_name_plural': '910 Contact forms'},
        ),
        migrations.AlterModelOptions(
            name='dancestyleweteach',
            options={'verbose_name': 'Heading And Body', 'verbose_name_plural': '5 Dance class photo details'},
        ),
        migrations.AlterModelOptions(
            name='facultiesprofile',
            options={'verbose_name': 'Details', 'verbose_name_plural': '6 Instructor details'},
        ),
        migrations.AlterModelOptions(
            name='funkfactorygallery',
            options={'verbose_name': 'Details', 'verbose_name_plural': '7 Gallery'},
        ),
        migrations.AlterModelOptions(
            name='homepictures',
            options={'verbose_name': 'Website Top Image', 'verbose_name_plural': '1 Website Carousel Image'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': 'Notice', 'verbose_name_plural': '3 Notice'},
        ),
        migrations.AlterModelOptions(
            name='ourdetail',
            options={'verbose_name': 'Details', 'verbose_name_plural': '8 our details *soon to be available'},
        ),
        migrations.AlterModelOptions(
            name='passwords',
            options={'verbose_name': 'Details', 'verbose_name_plural': '9 Experimental'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Reviews', 'verbose_name_plural': '8 Reviews'},
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='body',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='heading',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, upload_to='about_us'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='more_body',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='more_popup_image',
            field=models.ImageField(blank=True, upload_to='about_us'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='classabout',
            name='body',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='classabout',
            name='body2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='classabout',
            name='heading',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='classabout',
            name='heading2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 18, 25, 42, 705325)),
        ),
        migrations.AlterField(
            model_name='dancestyleweteach',
            name='class_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='dancestyleweteach',
            name='dance_style',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='dancestyleweteach',
            name='picture',
            field=models.ImageField(blank=True, upload_to='dance_styles'),
        ),
        migrations.AlterField(
            model_name='facultiesprofile',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='funkfactorygallery',
            name='description',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='funkfactorygallery',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='homepictures',
            name='body',
            field=models.CharField(blank=True, default=3, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepictures',
            name='images',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='carousel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 18, 25, 42, 700328)),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
