# Generated by Django 3.0.6 on 2020-05-10 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0038_auto_20200510_2130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passwords',
        ),
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': 'Details', 'verbose_name_plural': '911 Contact forms'},
        ),
        migrations.AlterModelOptions(
            name='facultiesprofile',
            options={'verbose_name': 'Details', 'verbose_name_plural': '7 Instructor details'},
        ),
        migrations.AlterModelOptions(
            name='funkfactorygallery',
            options={'verbose_name': 'Details', 'verbose_name_plural': '8 Gallery'},
        ),
        migrations.AlterModelOptions(
            name='ourdetail',
            options={'verbose_name': 'Details', 'verbose_name_plural': '910 our details'},
        ),
        migrations.AlterModelOptions(
            name='packages',
            options={'verbose_name': 'Details', 'verbose_name_plural': '6 Class Packages'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Reviews', 'verbose_name_plural': '9 Reviews'},
        ),
        migrations.AlterField(
            model_name='contactform',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 22, 8, 53, 92160)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 22, 8, 53, 71173)),
        ),
    ]
