# Generated by Django 3.0.6 on 2020-05-11 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0041_auto_20200511_0443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepictures',
            options={'ordering': ('-date',), 'verbose_name': 'Website Top Image', 'verbose_name_plural': '1 Website Carousel Image'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ('-date',), 'verbose_name': 'Notice', 'verbose_name_plural': '3 Notice'},
        ),
        migrations.AlterField(
            model_name='contactform',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 21, 5, 11, 22065)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 21, 5, 11, 17494)),
        ),
    ]
